name: form_app
description: A sample demonstrating different types of forms and best practices
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.20.0
  http: ^1.0.0
  json_annotation: any
  english_words: ^4.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  go_router: ^14.0.0
  shared_preferences: ^2.0.15
  flutter_rating_bar: ^4.0.0
  firebase_core: ^3.6.0
  # Firestore を利用する場合
  cloud_firestore: ^5.4.4
  # Authentication を利用する場合
  firebase_auth: ^5.3.1
  cloud_functions: ^5.1.3
  flutter_local_notifications: ^18.0.1
  google_generative_ai: ^0.4.6
  flutter_secure_storage: ^8.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  build_runner: ^2.1.8
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_icons:
  android: false  # iOSのみの場合はfalseに設定
  ios: true
  image_path: "assets/images/icon.png" 